<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifiers>win-x64</RuntimeIdentifiers>
    <VERSION Condition=" '$(VERSION)' == ''">4.0.0.0</VERSION>
    <Version>$(VERSION)</Version>
    <AssemblyVersion>$(VERSION)</AssemblyVersion>
    <FileVersion>$(VERSION)</FileVersion>
    <Copyright>Copyright © 2019-$([System.DateTime]::Now.ToString('yyyy'))</Copyright>
    <Description>An automated ModList installer</Description>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
   <!-- <IncludeSymbolsInSingleFile>true</IncludeSymbolsInSingleFile> -->
    <AssemblyName>Wabbajack</AssemblyName>
    <JsonSerializerIsReflectionEnabledByDefault>true</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>


  <PropertyGroup>
    <NoWarn>CS8600,CS8601,CS8618,CS8604,CS8632,CS1998</NoWarn>
  </PropertyGroup>

    <PropertyGroup>
        <ApplicationIcon>Resources\Icons\wabbajack.ico</ApplicationIcon>
    </PropertyGroup>


    <ItemGroup>
        <!-- TODO: These updates are currently required because CefSharp.Wpf specifies
             <Private>false</Private>, which means these libraries will not be specified in
             the .deps.json file, and so the CoreCLR wouldn't load these. -->
        <Reference Update="CefSharp">
            <Private>true</Private>
        </Reference>
        <Reference Update="CefSharp.Core">
            <Private>true</Private>
        </Reference>
        <Reference Update="CefSharp.Wpf">
            <Private>true</Private>
        </Reference>
    </ItemGroup>

	<ItemGroup>
    <None Remove="LoginManagers\Icons\mega-text.png" />
    <None Remove="LoginManagers\Icons\mega.png" />
    <None Remove="Readme.md" />
    <None Remove="Resources\Fonts\Atkinson-Hyperlegible-Italic-102.ttf" />
    <None Remove="Resources\Fonts\Atkinson-Hyperlegible-Regular-102.ttf" />
    <None Remove="Resources\Fonts\Gabarito-VariableFont_wght-BF651cdf1f55e6c.ttf" />
    <None Remove="Resources\Fonts\PrimaryFont-Bold.ttf" />
    <None Remove="Resources\Fonts\PrimaryFont-BoldItalic.ttf" />
    <None Remove="Resources\Fonts\PrimaryFont-Italic.ttf" />
    <None Remove="Resources\Fonts\PrimaryFont-Regular.ttf" />
    <None Remove="Resources\GameGridIcons\Fallout4.png" />
    <None Remove="Resources\GameGridIcons\SkyrimSpecialEdition.png" />
    <None Remove="Resources\Icons\middle_mouse_button.png" />
    <Compile Remove="ViewModels\Compiler\VortexCompilerVM.cs" />
    <Compile Remove="ViewModels\Installers\VortexInstallerVM.cs" />
    <None Update="Resources\libwebp_x64.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\libwebp_x86.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="VerbRegistration.tt">
      <Generator>TextTemplatingFileGenerator</Generator>
      <LastGenOutput>VerbRegistration.cs</LastGenOutput>
    </None>
    <Compile Update="VerbRegistration.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>VerbRegistration.tt</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DynamicData" />
    <PackageReference Include="Extended.Wpf.Toolkit">
      <NoWarn>NU1701</NoWarn>
    </PackageReference>
    <PackageReference Include="Fizzler.Systems.HtmlAgilityPack" />
    <PackageReference Include="FluentIcons.Wpf" />
    <PackageReference Include="Fody">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Genbox.AlphaFS" />
    <PackageReference Include="GitInfo">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Humanizer" />
    <PackageReference Include="MahApps.Metro" />
    <PackageReference Include="MathConverter" />
    <PackageReference Include="Microsoft-WindowsAPICodePack-Shell" />
    <PackageReference Include="Microsoft.AspNetCore.WebUtilities" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Microsoft.Web.WebView2" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="NLog.Extensions.Logging" />
    <PackageReference Include="Orc.FileAssociation" />
    <PackageReference Include="PInvoke.User32" />
    <PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" />
    <PackageReference Include="ReactiveUI" />
    <PackageReference Include="ReactiveUI.Fody" />
    <PackageReference Include="ReactiveUI.WPF" />
    <PackageReference Include="Sdl.MultiSelectComboBox" />
    <PackageReference Include="SharpCompress" />
    <PackageReference Include="Silk.NET.DXGI" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="System.Drawing.Common" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Private.Uri" />
    <PackageReference Include="System.Reactive" />
    <PackageReference Include="System.Text.Json" />
    <PackageReference Include="System.Text.RegularExpressions" />
    <PackageReference Include="WPFThemes.DarkBlend" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Wabbajack.CLI.Builder\Wabbajack.CLI.Builder.csproj" />
    <ProjectReference Include="..\Wabbajack.CLI\Wabbajack.CLI.csproj" />
    <ProjectReference Include="..\Wabbajack.Downloaders.Dispatcher\Wabbajack.Downloaders.Dispatcher.csproj" />
    <ProjectReference Include="..\Wabbajack.Reporting\Wabbajack.Reporting.csproj" />
    <ProjectReference Include="..\Wabbajack.Services.OSIntegrated\Wabbajack.Services.OSIntegrated.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Fonts\Gabarito-VariableFont_wght-BF651cdf1f55e6c.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <None Remove="LoginManagers\Icons\lovers_lab.png" />
    <EmbeddedResource Include="LoginManagers\Icons\lovers_lab.png" />
    <None Remove="LoginManagers\Icons\vector_plexus.png" />
    <EmbeddedResource Include="LoginManagers\Icons\mega-text.png" />
    <EmbeddedResource Include="LoginManagers\Icons\mega.png" />
    <EmbeddedResource Include="LoginManagers\Icons\vector_plexus.png" />

  </ItemGroup>

  <ItemGroup>
    <Reference Include="MegaApiClient">
      <HintPath>..\Wabbajack.Downloaders.Mega\lib\MegaApiClient\MegaApiClient.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
