<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <VERSION Condition=" '$(VERSION)' == ''">4.0.0.0</VERSION>
        <Version>$(VERSION)</Version>
        <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Wabbajack.Downloaders.GameFile\Wabbajack.Downloaders.GameFile.csproj" />
        <ProjectReference Include="..\Wabbajack.Downloaders.Http\Wabbajack.Downloaders.Http.csproj" />
        <ProjectReference Include="..\Wabbajack.Downloaders.Interfaces\Wabbajack.Downloaders.Interfaces.csproj" />
        <ProjectReference Include="..\Wabbajack.Downloaders.ManualSources\Wabbajack.Downloaders.ManualSources.csproj" />
        <ProjectReference Include="..\Wabbajack.Downloaders.Nexus\Wabbajack.Downloaders.Nexus.csproj" />
        <ProjectReference Include="..\Wabbajack.Downloaders.VerificationCache\Wabbajack.Downloaders.VerificationCache.csproj" />
        <ProjectReference Include="..\Wabbajack.Downloaders.WabbajackCDN\Wabbajack.Downloaders.WabbajackCDN.csproj" />
        <ProjectReference Include="..\Wabbajack.Networking.WabbajackClientApi\Wabbajack.Networking.WabbajackClientApi.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
        <PackageReference Include="Newtonsoft.Json" />
        <PackageReference Include="SharpCompress" />
        <PackageReference Include="SixLabors.ImageSharp" />
        <PackageReference Include="System.Drawing.Common" />
    </ItemGroup>

</Project>
