<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition=" '$(OS)' == 'Windows_NT'">net10.0-windows</TargetFramework>
    <TargetFramework Condition=" '$(OS)' != 'Windows_NT'">net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <RootNamespace>WabbajackAvalonia.Test</RootNamespace>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <NoWarn>CS8600;CS8601;CS8618;CS8604;CS1998</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" Version="1.55.2" />
    <PackageReference Include="Avalonia.Headless" Version="11.3.17" />
    <PackageReference Include="Avalonia.ReactiveUI" Version="11.3.9" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wabbajack.App.Avalonia\Wabbajack.App.Avalonia.csproj" />
  </ItemGroup>
</Project>
