<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Wabbajack.Downloaders.Interfaces\Wabbajack.Downloaders.Interfaces.csproj" />
        <ProjectReference Include="..\Wabbajack.VFS\Wabbajack.VFS.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="GameFinder.StoreHandlers.EADesktop" />
        <PackageReference Include="GameFinder.StoreHandlers.EGS" />
        <PackageReference Include="GameFinder.StoreHandlers.GOG" />
        <PackageReference Include="GameFinder.StoreHandlers.Origin" />
        <PackageReference Include="GameFinder.StoreHandlers.Steam" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
        <PackageReference Include="SharpCompress" />
        <PackageReference Include="SixLabors.ImageSharp" />
        <PackageReference Include="System.Drawing.Common" />
    </ItemGroup>

</Project>
