name: CI Tests

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'Wabbajack**'
      - '.github/workflows/**'
    branches: [ master ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.101
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release /p:Platform=x64
    - name: Test Wabbajack.Common.Test
      run: dotnet test --verbosity normal --configuration Release /p:Platform=x64 Wabbajack.Common.Test
    - name: Test Compression.BSA.Test
      run: dotnet test --verbosity normal --configuration Release /p:Platform=x64 Compression.BSA.Test
    - name: Test Wabbajack.VirtualFileSystem.Test
      run: dotnet test --verbosity normal --configuration Release /p:Platform=x64 Wabbajack.VirtualFileSystem.Test
    - name: Test Wabbajack.Test
      run: dotnet test --verbosity normal --configuration Release /p:Platform=x64 Wabbajack.Test
    - name: Test Wabbajack.App.Test
      run: dotnet test --verbosity normal --configuration Release /p:Platform=x64 Wabbajack.App.Test
    - name: Test Wabbajack.Server.Test
      run: dotnet test --verbosity normal --configuration Release /p:Platform=x64 Wabbajack.Server.Test
